from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any, Union
from datetime import date
from decimal import Decimal

class Evidence(BaseModel):
    source_text: str
    page_number: int
    bounding_box: Optional[List[float]] = None  # [x1, y1, x2, y2]
    confidence: float = 0.0
    extraction_source: str = "ocr"  # 'ocr', 'gemini', 'regex', etc.

class ExtractedField(BaseModel):
    value: Any
    evidence: Optional[Evidence] = None

class StringField(ExtractedField):
    value: Optional[str] = None

class DateField(ExtractedField):
    value: Optional[date] = None

class DecimalField(ExtractedField):
    value: Optional[Decimal] = None

class LineItem(BaseModel):
    description: StringField
    quantity: Optional[DecimalField] = None
    unit: Optional[StringField] = None
    unit_price: Optional[DecimalField] = None
    vat_rate: Optional[DecimalField] = None
    vat_amount: Optional[DecimalField] = None
    amount: DecimalField
    formula: Optional[str] = None  # Deterministically generated by Python

class Party(BaseModel):
    name: StringField
    vat: Optional[StringField] = None

class Invoice(BaseModel):
    invoice_number: StringField
    invoice_date: Optional[DateField] = None
    
    supplier: Party
    customer: Party
    
    amount_before_vat: DecimalField
    vat_amount: DecimalField
    total_amount_after_vat: DecimalField
    
    qr_code_present: bool = False
    qr_data: List[str] = Field(default_factory=list)
    
    line_items: List[LineItem] = Field(default_factory=list)
